<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Catalogue · Snap Foodd Admin</title></head><body>
<header><h1><a href="{{ route('admin.dashboard') }}">Snap Foodd Admin</a></h1><nav><a href="{{ route('admin.catalogue.index') }}">Catalogue</a> · <a href="{{ route('admin.orders.index') }}">Orders</a> · <a href="{{ route('admin.customers.index') }}">Customers</a> · <a href="{{ route('admin.delivery-partners.index') }}">Delivery partners</a> · <a href="{{ route('admin.assignments.index') }}">Assignments</a> · <a href="{{ route('admin.invoices.index') }}">Invoices</a><form method="POST" action="{{ route('admin.logout') }}" style="display:inline">@csrf<button type="submit">Sign out</button></form></nav></header>
<main><h2>Catalogue management</h2>
@if (session('status'))<p role="status">{{ session('status') }}</p>@endif
@if ($errors->any())<div role="alert"><p>Please correct the following:</p><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="GET"><label>Search categories/products <input type="search" name="q" maxlength="120" value="{{ $validated['q'] ?? '' }}"></label><label>Type <select name="type"><option value="all" @selected(($validated['type'] ?? 'all') === 'all')>All</option><option value="categories" @selected(($validated['type'] ?? '') === 'categories')>Categories</option><option value="products" @selected(($validated['type'] ?? '') === 'products')>Products</option></select></label><button type="submit">Search</button><a href="{{ route('admin.catalogue.index') }}">Clear</a></form>
<section><h3>Create category</h3><form method="POST" action="{{ route('admin.catalogue.categories.store') }}">@csrf<label>Name <input name="name" required maxlength="120"></label><label>Slug <input name="slug" required maxlength="140"></label><label>Image URL <input name="image" type="url" maxlength="2048"></label><label>Sort order <input name="sort_order" type="number" min="0" value="0"></label><label><input type="checkbox" name="is_active" value="1" checked> Active</label><button type="submit">Create category</button></form></section>
<section><h3>Categories</h3><table><thead><tr><th>Name / slug</th><th>Products</th><th>Active</th><th>Update</th><th>Deactivate</th></tr></thead><tbody>
@forelse ($categories as $category)<tr><td>{{ $category->name }}<br>{{ $category->slug }}</td><td>{{ $category->products_count }}</td><td>{{ $category->is_active ? 'Yes' : 'No' }}</td><td><form method="POST" action="{{ route('admin.catalogue.categories.update', $category) }}">@csrf @method('PATCH')<label>Name <input name="name" value="{{ $category->name }}" required maxlength="120"></label><label>Slug <input name="slug" value="{{ $category->slug }}" required maxlength="140"></label><label>Image URL <input name="image" type="url" value="{{ $category->image }}" maxlength="2048"></label><label>Sort order <input name="sort_order" type="number" min="0" value="{{ $category->sort_order }}"></label><label><input type="checkbox" name="is_active" value="1" @checked($category->is_active)> Active</label><button type="submit">Save</button></form></td><td><form method="POST" action="{{ route('admin.catalogue.categories.deactivate', $category) }}">@csrf<button type="submit" @disabled(!$category->is_active)>Deactivate</button></form></td></tr>
@empty<tr><td colspan="5">No categories found.</td></tr>@endforelse
</tbody></table>{{ $categories->links() }}</section>
<section><h3>Create product</h3><form method="POST" action="{{ route('admin.catalogue.products.store') }}">@csrf<label>Category <select name="category_id" required>@foreach ($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label>Name <input name="name" required maxlength="180"></label><label>Slug <input name="slug" required maxlength="200"></label><label>Description <textarea name="description"></textarea></label><label>Price <input name="price" type="number" min="0" step="0.01" required></label><label>Image URL <input name="image" type="url" maxlength="2048"></label><label>Stock quantity <input name="stock_quantity" type="number" min="0" value="0"></label><label><input type="checkbox" name="is_available" value="1" checked> Available</label><label><input type="checkbox" name="is_active" value="1" checked> Active</label><button type="submit">Create product</button></form></section>
<section><h3>Products</h3><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Availability</th><th>Update</th><th>Deactivate</th></tr></thead><tbody>
@forelse ($products as $product)<tr><td>{{ $product->name }}<br>{{ $product->slug }}</td><td>{{ $product->category?->name }}</td><td>{{ $product->price }}</td><td>{{ $product->is_active ? 'Active' : 'Inactive' }} / {{ $product->is_available ? 'Available' : 'Unavailable' }}</td><td><form method="POST" action="{{ route('admin.catalogue.products.update', $product) }}">@csrf @method('PATCH')<label>Category <select name="category_id" required>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected($product->category_id === $category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Name <input name="name" value="{{ $product->name }}" required maxlength="180"></label><label>Slug <input name="slug" value="{{ $product->slug }}" required maxlength="200"></label><label>Description <textarea name="description">{{ $product->description }}</textarea></label><label>Price <input name="price" type="number" min="0" step="0.01" value="{{ $product->price }}" required></label><label>Image URL <input name="image" type="url" value="{{ $product->image }}" maxlength="2048"></label><label>Stock quantity <input name="stock_quantity" type="number" min="0" value="{{ $product->stock_quantity }}"></label><label><input type="checkbox" name="is_available" value="1" @checked($product->is_available)> Available</label><label><input type="checkbox" name="is_active" value="1" @checked($product->is_active)> Active</label><button type="submit">Save</button></form></td><td><form method="POST" action="{{ route('admin.catalogue.products.deactivate', $product) }}">@csrf<button type="submit" @disabled(!$product->is_active)>Deactivate</button></form></td></tr>
@empty<tr><td colspan="6">No products found.</td></tr>@endforelse
</tbody></table>{{ $products->links() }}</section>
</main></body></html>
